spring.application.name=back

# Active Profile (dev or prod)
spring.profiles.active=dev

# Import Secret Configuration
spring.config.import=optional:classpath:application-secret.properties

# Database Configuration
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${oauth2.google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${oauth2.google.client-secret}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# JWT Configuration
jwt.secret=${jwt.secret}
jwt.expiration=1800000
jwt.refresh-expiration=604800000
